#!/bin/bash
'''
    This program plays online radios...
    Copyright (C) 2015 Appavoo Vara ;)
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
clear
if command mplayer > /dev/null
then
	echo "Which radio station do you want to tune in?"
	echo "1. RadioPlus"
	echo "2. Top FM"
	echo "3. Best FM"
	echo "4. RadioONE"
	echo "5. Taal FM"
	echo "6. Kool FM"
	echo "7. Music FM"
	echo "8. Radio Mauritius"
	echo "9. Radio Moris"

	echo "Enter 1, 2, 3, ... to select or any other thing to quit!"
	read choice
	if test $choice -eq "1" 
	then
		echo "You are now listening to RadioPlus..."
		mplayer -cache 1024 mms://mediaserver.intnet.mu/radioplus
	elif test $choice -eq "2" 
	then
		echo "You are now listening to TopFM..."
		mplayer mms://mediaserver.intnet.mu/topfm
	elif test $choice -eq "3" 
	then
		echo "You are now listening to BestFM..."
		mplayer mms://mediaserver.intnet.mu/bestfm
	elif test $choice -eq "4" 
	then
		echo "You are now listening to RadioONE..."
		mplayer http://mu1.frekance.com:8585/128kbps
	elif test $choice -eq "5" 
	then
		echo "You are now listening to Taal FM..."
		mplayer mms://mediaserver.intnet.mu/mbctaalfm
	elif test $choice -eq "6" 
	then
		echo "You are now listening to Kool FM..."
		mplayer mms://mediaserver.intnet.mu/mbckoolfm
	elif test $choice -eq "7" 
	then
		echo "You are now listening to Music FM..."
		mplayer mms://mediaserver.intnet.mu/mbcmusicfm
	elif test $choice -eq "8" 
	then
		echo "You are now listening to Radio Mauritius..."
		mplayer mms://mediaserver.intnet.mu/mbcrm2
	elif test $choice -eq "9" 
	then
		echo "You are now listening to Radio Moris..."
		mplayer mms://mediaserver.intnet.mu/mbcrm1
	else
		clear
		echo "Bye."
	fi
else
	echo "You need mplayer to listen to a radio station."
	echo "To install mplayer on your CentOS, type:"
	echo "sudo yum install mplayer"
	echo "Bye."
fi
